In [1]:
import torch

In [2]:
x = torch.ones((2,1))
y = x.view(-1, )
y[-1] = 0


In [4]:

import numpy as np


In [8]:
x = torch.randn(1, device='cpu')

In [6]:
x.numpy()

TypeError: ignored

In [10]:
x.numpy()

array([0.2594141], dtype=float32)

In [11]:
torch.tensor([1,2,3]).size()

torch.Size([3])

In [12]:
f = torch.randn((2,6))
w = torch.randn((2,6))

In [17]:
torch.mm(f, w.reshape(6,2))

tensor([[ 0.6351,  1.0629],
        [-1.8050, -0.5814]])

In [19]:
d = np.array([
              [1,2,3],
              [1,2,3],
              [1,2,3],
              ])
dt = torch.as_tensor(d)
d[1] = [0,1,2]
d[2] = [5]
print(dt)

tensor([[1, 2, 3],
        [0, 1, 2],
        [5, 5, 5]])
